version: "3.7"

services:
  login-api-service:
    build: .
    ports:
      - 9090:8080
    restart: on-failure
    networks:
      - my-network
    depends_on:
      - mysql-service

  mysql-service:
    image: mysql:latest
    environment:
      - MYSQL_ROOT_PASSWORD=${DBPass}
    ports:
      - 3306
    volumes:
      - /home/dikoc/mysql:/var/lib/mysql
      - ./mysql/schema.sql:/docker-entrypoint-initdb.d/init.sql
    command: --init-file /docker-entrypoint-initdb.d/init.sql
    networks:
      - my-network

networks:
  my-network:
    driver: bridge
